### ISSUE TITLE
Add composite feature

### ISSUE THREAD

**Issue by phillip-kruger** [mvnpm/mvnpm#5]
Find a clean way to group multiple libs into one. This will reduce the number of downloads for example a vaadin project that at the moment makes up 53 jars

**Comment by ia3andy** [comment]
IMO, the easiest way is just to put it all in one jar without modification, and combine all the dependencies in the pom
you can just split in different directories and use a specific directory `_grouped` or something so that the client library knows that it should look for multiple packages.


For the importmap, we can either merge or have multiple importmap (but better merge I guess)

**Comment by phillip-kruger** [comment]
And package.json ? multiple in subfolder ?

**Comment by ia3andy** [comment]
> And package.json ? multiple in subfolder ?

yes, it's already what's done in some libraries. e.g. https://www.npmjs.com/package/react-bootstrap?activeTab=code (look at the different dirs)

and it's also what's done in node_modules. For web-bundler (or I guess any other client) if we flag it as a group and copy all the directories, the end result is the exact same as having them split..
